### ISSUE TITLE
Request for input generation code

### ISSUE THREAD

**Issue by quito418** [itmoon7/onconpc#1]
Hi Onconpc team,

I am really interested in trying out your work using a custom Cancer dataset.
Would it be possible for you to share the input processing code with me? 
Having this code would be immensely helpful for adapting your work to custom dataset.

Thanks

**Comment by itmoon7** [comment]
Thank you for reaching out. A pre-processing script is already available at [this GitHub link](https://github.com/itmoon7/onconpc/blob/main/codes/process_features_profile_genie_v2.py). It should be compatible with the public AACR GENIE data, which you can request [here](https://www.aacr.org/professionals/research/aacr-project-genie/aacr-project-genie-data/), and may require minimal adjustments, if any. Feel free to contact us with any additional questions!

**Comment by itmoon7** [comment]
Thank you for reaching out. A pre-processing script is already available at [this GitHub link](https://github.com/itmoon7/onconpc/blob/main/codes/process_features_profile_genie_v2.py). It should be compatible with the public AACR GENIE data, which you can request [here](https://www.aacr.org/professionals/research/aacr-project-genie/aacr-project-genie-data/), and may require minimal adjustments, if any. Feel free to contact us with any additional questions!

**Comment by quito418** [comment]
Thanks for your prompt response and providing the GitHub link to the pre-processing script for AACR GENIE data.
