### ISSUE TITLE
some questions about the input data

### ISSUE THREAD

**Issue by tb1over** [itmoon7/onconpc#4]
Thank your for share your work, i have some problems about this work:
1. the inputdata:  i do not konw where to download or how the generate the input data dir , for example the `dfci/profile_samples_info` in process_features.py;
2. `dfci/profile_mutation_dfci` in process_features.py; i canot find this file in the [synapse](https://www.synapse.org/#!Synapse:syn7222066/wiki/405659), which descript in the manuscript

**Comment by itmoon7** [comment]
Thank you for reaching out! Files in the dfci directory are confidential institutional data. Nonetheless, you should still be able to process features and train the classifier using publicly available AACR GENIE data by commenting out the the code sections related to the institutional data. Please feel free to reach out if you face further issues.
